### ISSUE TITLE
AKS using kubernetes LB - console-ui-ext has no external IP

### ISSUE THREAD

**Issue by svollath** [SUSE/stratos#13]
### Frontent Deployment type

* [ ] Cloud Foundry Application (cf push)
* [x] Kubernetes, using a helm chart
* [ ] Docker, using docker compose
* [ ] Docker, single container deploying all components
* [ ] npm run start
* [x] Other (please specify below)
Azure AKS using the kubernetes LoadBalancer

### Backend (portal-proxy) Deployment type

* [ ] Cloud Foundry Application (cf push)
* [x] Kubernetes, using a helm chart
* [ ] Docker, using docker compose
* [ ] Docker, single container deploying all components
* [x] Other (please specify below)
Azure AKS using the kubernetes LoadBalancer

### Expected behaviour
Stratos is deployed using the same scf-config-values.yaml file as for uaa, and scf. It should get a LoadBalanced public IP automatically, when `external_ips` is missing and `loadbalanced` is true:

example scf-config-values.yaml:
```
secrets:
    CLUSTER_ADMIN_PASSWORD: changeme
    UAA_ADMIN_CLIENT_SECRET: uaa-admin-client-secret

env:
    DOMAIN: svlb.susecap.net
    UAA_HOST: uaa.svlb.susecap.net
    UAA_PORT: 2793
    GARDEN_ROOTFS_DRIVER: "overlay-xfs"

kube:
    storage_class:
        persistent: "default"
        shared: "shared"

    registry:
       hostname: "staging.registry.howdoi.website"
       username: ""
       password: ""
    organization: "splatform"

    auth: none

services:
  loadbalanced: true
```

There should be `console-ui-ext-public` like with:

```
diego-access-public    LoadBalancer   10.0.22.62     40.118.56.197    2222:32044/TCP
```

### Actual behaviour
console-ui-ext has no EXTERNAL IP:

```
> kubectl --namespace stratos get svc console-ui-ext
NAME             TYPE       CLUSTER-IP   EXTERNAL-IP   PORT(S)                      AGE
console-ui-ext   NodePort   10.0.34.56   <none>        80:32127/TCP,443:30718/TCP   19m
```

### Steps to reproduce the behavior
see https://trello.com/c/sQGhnAwJ

### Log output covering before error and any error statements
```
Insert log hereCopy
```
